# Be sure to restart your server when you modify this file.

default: &default
  localeapp_api_key:    <%= ENV["LOCALEAPP_API_KEY"] || 'dummy_key' %>
  pupesoft_install_dir: <%= ENV["PUPESOFT_INSTALL_DIR"] || '/home/devlab/pupesoft' %>

development:
  <<: *default
  secret_key_base: 9f8cc2a817a6e0e52c649957ca661306dee57394a6642021e16a1dca20a3ae9d287ef724e9ba9605811ad16de8f0e6debb0387850e1041770a36a3dc4cc425fa
  db_host:         <%= ENV['PUPESOFT_DEVELOPMENT_HOSTNAME'] %>
  db_name:         <%= ENV['PUPESOFT_DEVELOPMENT_DATABASE'] %>
  db_user:         <%= ENV['PUPESOFT_DEVELOPMENT_USERNAME'] %>
  db_pass:         <%= ENV['PUPESOFT_DEVELOPMENT_PASSWORD'] %>
  db_port:         <%= ENV["PUPESOFT_DEVELOPMENT_DATABASE_PORT"] || '3306' %>
  db_pool:         <%= ENV["PUPESOFT_DEVELOPMENT_DATABASE_POOL"] || '5' %>

test:
  <<: *default
  secret_key_base: 68c00c0990ac338e098802cf7f87082a13c56893894e65d83216438c0238c944c593cb2578d8270fce35234097a2d873d8d961509d499d65b85221de39223d77
  db_host:         <%= ENV['PUPESOFT_TEST_HOSTNAME'] %>
  db_name:         <%= ENV['PUPESOFT_TEST_DATABASE'] %>
  db_user:         <%= ENV['PUPESOFT_TEST_USERNAME'] %>
  db_pass:         <%= ENV['PUPESOFT_TEST_PASSWORD'] %>
  db_port:         <%= ENV["PUPESOFT_TEST_DATABASE_PORT"] || '3306' %>
  db_pool:         <%= ENV["PUPESOFT_TEST_DATABASE_POOL"] || '5' %>

production:
  <<: *default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  db_host:         <%= ENV['PUPESOFT_PRODUCTION_HOSTNAME'] %>
  db_name:         <%= ENV['PUPESOFT_PRODUCTION_DATABASE'] %>
  db_user:         <%= ENV['PUPESOFT_PRODUCTION_USERNAME'] %>
  db_pass:         <%= ENV['PUPESOFT_PRODUCTION_PASSWORD'] %>
  db_port:         <%= ENV["PUPESOFT_PRODUCTION_DATABASE_PORT"] || '3306' %>
  db_pool:         <%= ENV["PUPESOFT_PRODUCTION_DATABASE_POOL"] || '5' %>
